export enum PromotionTypeEnum {
  PLATINUM = 'Platinum',
  SILVER = 'Silver',
  GOLD = 'Gold',
  QUICKIE = 'Tino Quickie',
}

export enum PromotionEventsEnum {
  START_ACCOUNT_PROMOTION_EVENT = 'START_ACCOUNT_PROMOTION_EVENT',
  END_ACCOUNT_PROMOTION_EVENT = 'END_ACCOUNT_PROMOTION_EVENT',
  CONTINUE_ACCOUNT_PROMOTION_EVENT = 'CONTINUE_ACCOUNT_PROMOTION_EVENT',
}
