export enum PaymentEvents {
  DISBURSE_PAYMENT_EVENT = 'DISBURSE_PAYMENT_EVENT',
}

export enum LicenseEvents {
  LICENSE_EXPIRED_EVENT = 'LICENSE_EXPIRED_EVENT',
  DE_LIST_LISTINGS_EVENT = 'DE_LIST_LISTINGS_EVENT',
  GOVERNMENT_ISSUED_ID_EXPIRED_EVENT = 'GOVERNMENT_ISSUED_ID_EXPIRED_EVENT',
  DE_LIST_GOVERNMENT_ISSUED_ID_EVENT = 'DE_LIST_GOVERNMENT_ISSUED_ID_EVENT',
}
